### ISSUE TITLE
Want to add features: gjson

### ISSUE THREAD

**Issue by losenli** [imroc/req#158]
Want to add features: gjson
```
func (r *Response) G(path string) (gjson.Result, error) {
	if r.Err != nil {
		return gjson.Result{}, r.Err
	}
	ctxType := r.Header.Get("Content-Type")
	if !strings.Contains(ctxType, "json") {
		return gjson.Result{}, errors.New("Json only supported")
	}
	// return gjson.Result
	return gjson.GetBytes(r.Bytes(), path), nil
}
```

```
func main() {
	url := "https://openapi.dvr163.com/message/nonce?method=get"

	resp := req.MustGet(url)

	result, _ := resp.G("request_id")
	fmt.Println(result.String())
}
```

**Comment by imroc** [comment]
Nice catch, but I don't think it's a good idea to have gjson built into req, because this will increase the req dependency, which may lead to version conflicts in some projects. It will also increase compiled binary size of projects that do not need to rely on gjson.

This logic is actually very simple, you can combine req and gjson by yourself to expand the capabilities.

I just updated the official documentation to include this usage example, refer to https://req.cool/docs/tutorial/handle-response/#combine-with-gjson-to-get-json-fields-easily

**Comment by losenli** [comment]
有道理，本来也是基于自己90%以上都是json格式请求场景  的个人想法。
